examples/react/src/App.tsx, src/hooks/use-category-tree.tsx
- Removidos filtros do hook de Category Tree
=> [Hotfix] Ajustes Hook Category Tree

src/env.d.ts, src/hooks/use-cart.tsx, src/hooks/use-products.tsx
- Ajuste em nomenclatura de mock de product para products (lista)
- Ajuste  nomenclatura de state de hook de product (showcase para product)
[[Hotfix] Ajustes mock de product ](https://github.com/uxshop/storefront-core/pull/32)
=> [Hotfix] Ajustar mock product

src/hooks/use-shop.tsx
- Adicionado await em hook de shop
=> [Hotfix] Ajuste hook shop

src/components/sections/index.tsx
- Removido o filtro de `{page: "home"}` das sections
=> [Hotfix] Remover filtro de page

src/hooks/use-cart.tsx
- Ajustes em lógica de busca de cookie em hook de cart
[[Hotfix] Ajustes no input da query de cart](https://github.com/uxshop/storefront-core/pull/38)
=> [Hotfix] Ajustes em hook de cart

examples/react/src/App.tsx, src/hooks/use-blog-posts.tsx
=> [Task] Integracao do blog post - Ajustes em service de blog post

examples/react/src/App.tsx, src/hooks/use-blog-categories.tsx
- Ajustados parametros em hook de blog category
=> [Task] Integracao do blog post - Ajustes em hook de blog category

examples/react/src/App.tsx, src/hooks/use-blog-categories.tsx, src/hooks/use-blog-posts.tsx
=> [Feat] Integracao blog

src/hooks/use-blog-posts.tsx
- Ajuste interface de parametro de hook
=> [Hotfix] Ajuste parametro hook

src/hooks/use-blog-posts.tsx
[[Task] Integracao blog post](https://dev.azure.com/doocacom/Platform/_workitems/edit/3624)
- Ajuste em dependencia de hook
=> [Feat] Integracao blog post

src/hooks/use-blog-posts.tsx
- Adicionada dependencia de fast search em blog post
=> [Feat] Iintegracao blog

src/hooks/use-blog-posts.tsx
- Adicionado try catch em hook
=> [Hotfix] Ajuste hook post

src/hooks/use-blog-posts.tsx
- Ajuste em hook para contemplar mudança em interface
=> [Hotfix] Ajustes em atributos para contemplar  interfaces

src/hooks/use-menus.tsx, src/routes/default-routes.ts
- Corrigida dependência do useEffect do hook useMenu
- Corrido o path no import do arquivo `HelpersTypes`
=> [Hotfix] Dependência no useEffect do useMenu

src/hooks/use-apps.tsx
- Corrigido import de service e interface
=> [Hotfix] Ajuste import service/interface de app

package.json
- Atualizada versão de node types
=> [Hotfix] Auste de versão de pacote node types

src/hooks/use-apps.tsx
- Adiciona trycatch para retornar um objeto de erro
=> [Task] Tratar hook use-apps

src/components/ux/ux-video/index.tsx, src/components/ux/ux-video/types.ts
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront-4?workitem=4671)
- feito refactor no wrapper (o componente ja existia)
=> [task] Criar wrapper no react do componente ux-video

src/components/ux/ux-text-image/index.tsx, src/components/ux/ux-text-image/types.ts
[task link](xxxxxxxxxx)
- refatorado o wrapper de ux-text-image (o componente ja existia)
=> [task] Criar wrapper no react do componente ux-text-image

src/hooks/use-blog-posts.tsx
=> [Task]: Tratar erro no Hook use-blog-posts

src/hooks/use-freights.tsx
=> [Task Tratar erro no Hook use-freights

examples/react/src/App.tsx, src/hooks/use-category-tree.tsx
=> [Task]: Tratar erro no Hook use-category-tree

src/hooks/use-blog-categories.tsx
=> [Task]: Tratar erro no Hook use-blog-categories

src/hooks/use-landing-pages.tsx
=> [Task] Tratar erro no Hook use-landing-pages

src/hooks/use-menus.tsx
=> [Task] Tratar erro no Hook use-menus

src/hooks/use-pages.tsx, src/hooks/use-scripts.tsx
- implementa logica que retorna data e erro do hook useScripts
=> [Task] Tratar erro no Hook use-scripts

src/hooks/use-sections.tsx
- Tratar o erro nas buscas da API retornando um objeto com erro ou data.
=> [Task] Tratar erro no Hook use-sections

src/hooks/use-settings.tsx
=> [Task] Tratar erro no Hook use-settings

src/hooks/use-shop.tsx
- Tratar o erro nas buscas da API retornando um objeto com erro ou data.
=> [Task] Tratar erro no Hook use-shop

src/hooks/use-sidebar.tsx
=> [Task[ Tratar erro no Hook use-sidebar

src/hooks/use-blog-posts.tsx
=> [Hotfix] Remove parametros repetidos

src/hooks/use-user.tsx
- Tratar o erro nas buscas da API retornando um objeto com erro ou data.
=> [Task] Tratar erro no Hook use-user

src/components/ux/ux-video/types.ts
- corrigido ordem das props de ux-video
=> [fix] corrigir ordem de props (ux-video)

src/components/sections/index.tsx, src/hooks/types/HookData.ts, src/hooks/use-apps.tsx, src/hooks/use-blog-categories.tsx, src/hooks/use-blog-posts.tsx, src/hooks/use-brands.tsx, src/hooks/use-category-tree.tsx, src/hooks/use-category.tsx, src/hooks/use-freights.tsx, src/hooks/use-landing-pages.tsx, src/hooks/use-menus.tsx, src/hooks/use-newsletter.tsx, src/hooks/use-pages.tsx, src/hooks/use-products.tsx, src/hooks/use-scripts.tsx, src/hooks/use-sections.tsx, src/hooks/use-settings.tsx, src/hooks/use-shop.tsx, src/hooks/use-sidebar.tsx, src/hooks/use-user.tsx
- Ajustes hooks com nova estrutura
=> [Hotfix] Ajusta estrutura de hooks

src/hooks/use-menus.tsx
- Adicionada dependência de id de menu no hook use-menus
=> [Fix] Dependência de id de menu

src/components/ux/ux-carousel/index.tsx, src/components/ux/ux-carousel/types.ts, src/components/ux/ux-showcase/index.tsx, src/components/ux/ux-showcase/types.ts, src/routes/default-routes.ts
[task link](xxxxxxxxxx)
- corrigido componentes que nao recebiam filhos
- adicionado rotas novas para testes
=> [task] Revisar e montar página com sections de landing-page

src/components/ux/ux-showcase-item/index.tsx, src/components/ux/ux-showcase/index.tsx
corrigido ordem de imports de:
- ux-showcase
- ux-showcase-item
=> [fix] corrigir ordem de imports

src/components/ux/ux-carousel/index.tsx, src/components/ux/ux-carousel/types.ts, src/components/ux/ux-showcase-item/index.tsx, src/components/ux/ux-showcase/index.tsx, src/components/ux/ux-showcase/types.ts
[feat link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront-5?workitem=3319)
- corrigido de componentes wrapper que nao recebiam filhos
=> [feat] Cadastro de landingpages

src/hooks/use-sidebar.tsx
=> [Hotfix] Ajuste em hook de sidebar

src/hooks/use-newsletter.tsx
- Adiciona retorno de função subscribe
=> [Hotfix]: Corrige useNewsletter

src/hooks/use-sidebar.tsx
- Ajuste em hook de sidebar para parametro contemplar filtros novos
Mergear depois de:
https://github.com/uxshop/storefront-core/pull/117
=> [Hotfix] Ajustar parametro de hook de sidebar

src/hooks/use-brands.tsx, src/hooks/use-category.tsx
- Adição da dependência de `id` e `slug` nos hooks de `brand` e `category`
=> [Hotfix] Adicionar dependência em marca e categoria

src/components/landing-page-sections/ux-showcase-item/index.tsx, src/components/landing-page-sections/ux-showcase-item/types.ts, src/components/landing-page-sections/ux-showcase/index.tsx, src/components/landing-page-sections/ux-showcase/types.ts
[fix link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront-5?workitem=5198)
- corrigido renderização do item no landing-editor
=> [fix] Componente de Vitrine de Produto

src/components/landing-page-sections/ux-text-image/index.tsx, src/components/landing-page-sections/ux-text-image/types.ts
[fix link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront-5?workitem=5235)
- corrigido renderização do componente para o landing-editor
=> [fix] Componente TextImage

src/components/landing-page-sections/ux-testimonials/index.tsx, src/components/landing-page-sections/ux-testimonials/types.ts
Altera propiedades de UXTestmonials
=> [Fix] Componente UXTestimonials

src/components/landing-page-sections/ux-carousel-item/index.tsx, src/components/landing-page-sections/ux-carousel-item/types.ts, src/components/landing-page-sections/ux-carousel/index.tsx, src/components/landing-page-sections/ux-carousel/types.ts
[fix link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront-5?workitem=5197)
- corrigido wrapper de carousel e carousel item para o landing-editor
=> [fix] Componente Carrossel e Carrossel Item

src/hooks/use-settings.tsx
- Adicionada dependência de themeId na execução do hook use-settings
=> [Hotfix] Adicionada dependência de themeId na execução do hook

src/components/landing-page-sections/ux-banners/types.ts, src/components/landing-page-sections/ux-testimonials/index.tsx, src/components/landing-page-sections/ux-testimonials/types.ts, src/components/section-loader/index.tsx
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront-6?workitem=5511)
Changes:
=> [task]: Refatora componente react ux-testimonials

src/components/product-microdata/types.ts
- Ajustada interface de product;
=> [Task] Adicionar componentes de dados estruturados de product e product list

src/components/meta-seo/partials/default-tags.tsx, src/components/meta-seo/partials/facebook-tags.tsx, src/components/meta-seo/partials/twitter-tags.tsx
[task link](https://dev.azure.com/doocacom/Platform/_workitems/edit/5485)
- Adicionados operadores optional em componentes de metatag;
=> [Feat] Adicionar componente de metatags

src/components/landing-page-sections/ux-banners/types.ts, src/components/meta-seo/partials/default-tags.tsx, src/components/meta-seo/partials/facebook-tags.tsx, src/components/meta-seo/partials/twitter-tags.tsx, src/components/product-microdata/types.ts
Ajuste nos componentes "Texto e Imagem", "Depoimentos" e "Banner"
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront-7?workitem=5780)
Changes:
Remove prop não utilizada
=> [Task] Ajuste nos componentes da landing page

src/components/sections/index.tsx, src/hooks/use-blog-posts.tsx
- Adição do filtro de page
- Adição da dependência de quantidade de registros de posts a serem buscados
=> [Task] Seleção de páginas

src/hooks/use-blog-categories.tsx, src/hooks/use-blog-posts.tsx
Revisa dados blog
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront-7?workitem=5700)
Changes:
- Adiciona `slug` e `id` no vetor de atualização do `use-blog-post`
=> [Task] Revisa dados blog
